let products = [
    {
        "id": 1001,
        "title": "Maths",
        "location": "London",
        "price": 25,
        "image": "images/maths.png",
        "availableInventory": 5,
        "rating":5,
    },
    {
        "id": 1002,
        "title": "English",
        "location": "Birmingham",
        "price": 20,
        "image": "images/english.png",
        "availableInventory": 5,
        "rating":3,
    },
    {
        "id": 1003,
        "title": "Science",
        "location": "Manchester",
        "price": 25,
        "image": "images/science.png",
        "availableInventory": 5,
        "rating":2,
    },
    {
        "id": 1004,
        "title": "Geography",
        "location": "Leeds",
        "price": 15,
        "image": "images/geography.png",
        "availableInventory": 5,
        "rating":3,
    },
    {
        "id": 1005,
        "title": "History",
        "location": "Cardiff",
        "price": 30,
        "image": "images/history.png",
        "availableInventory": 5,
        "rating":4,
    },
    {
        "id": 1006,
        "title": "ICT",
        "location": "Glasgow",
        "price": 10,
        "image": "images/ICT.png",
        "availableInventory": 5,
        "rating":5,
    },
    {
        "id": 1007,
        "title": "Law",
        "location": "Liverpool",
        "price": 40,
        "image": "images/law.png",
        "availableInventory": 5,
        "rating":1,
    },
    {
        "id": 1008,
        "title": "Economics",
        "location": "Edinburgh",
        "price": 45,
        "image": "images/economics.png",
        "availableInventory": 5,
        "rating":2,
    },
    {
        "id": 1009,
        "title": "Spanish",
        "location": "York",
        "price": 17,
        "image": "images/spanish.png",
        "availableInventory": 5,
        "rating":4,
    },
    {
        "id": 1010,
        "title": "Psychology",
        "location": "Bath",
        "price": 13,
        "image": "images/psychology.png",
        "availableInventory": 5,
        "rating":2,
    },
]